site_name: ZincSearch

# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin required for nav
plugins:
  - search
#   - awesome-pages
# nav:
#   - index.md
#   - getting-started.md
#   - installation.md
#   - ...
#   - monitoring.md
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/zincsearch
    - icon: fontawesome/brands/github 
      link: https://github.com/zinclabs/zinc
    - icon: fontawesome/brands/docker 
      link: https://gallery.ecr.aws/h9e2j3o7/zinc
    - icon: fontawesome/brands/slack 
      link: https://join.slack.com/t/zinc-nvh4832/shared_invite/zt-11r96hv2b-UwxUILuSJ1duzl_6mhJwVg
  generator: false
  version:
    provider: mike
  analytics:
    provider: google
    property: G-ZM6P0XB94J
theme:
  name: material
  custom_dir: overrides
  features:
    # - navigation.expand
    - navigation.instant
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
repo_url: https://github.com/zinclabs/zinc
repo_name: zinclabs/zinc
edit_uri: https://github.com/zinclabs/zincsearch-docs/edit/main/docs/
markdown_extensions:
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

